spring:
  application:
    name: service-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    store:
      service-id: service-store
      path: /api/store/**
    vehicle:
      service-id: service-vehicle
      path: /api/vehicle/**
    user:
      service-id: service-user
      path: /api/us/**
ribbon:
  ConnnectTimeout: 3000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000